### ISSUE TITLE
Не сохраняется опция Fast translation

### ISSUE THREAD

**Issue by lucerion** [johnner/tran#21]
Версия: 1.2.5
Версия Chrome: 47.0

При попытке сохранить настройки:
```
Uncaught TypeError: Cannot read property 'checked' of null
  get	@	options.js:195
  save	@	options.js:41
  (anonymous function)	@	options.js:225
```

При открытии страницы настроек:
````
Uncaught TypeError: Cannot read property 'addEventListener' of null
  (anonymous function) @ options.js:227

Error in response to storage.get: TypeError: Cannot set property 'checked' of null
    at Options.set (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:202:51)
    at Options.onRestore (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:65:20)
    at Object.callback (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:80:18)
    at Options.storage (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:79:29)
    at Options.restore (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:31:12)
    at HTMLDocument.<anonymous> (chrome-extension://lhjldahfbiadelganmhjiolblffjjgok/js/options.js:224:11)
```

**Comment by johnner** [comment]
fixed
